import type { Metadata } from "next";
import "../globals.css";
import Header from "@/app/_components/header/Header";
import Footer from "@/app/_components/footer/Footer";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "ASBC",
  description: "Generated by ASBC Software Solutions",
};

export default function PagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="light"
      disableTransitionOnChange
    >
      <div className="relative z-10">
        <Header />
      </div>
      <main className="grow">{children}</main>
      <Footer />
    </ThemeProvider>
  );
}
